version: '3'
services:
    log-reader:
        build:
            dockerfile: ./docker/Dockerfile
            context: .
        container_name: log-reader
        volumes:
          - ./src:/usr/local/go/src/log-reader/src
        networks: 
            - logreader-network
        depends_on:
            - mongodb

    mongodb:
        image: mongo:4.4.3
        logging:
          driver: "none"
        container_name: mongodb
        networks: 
            - logreader-network
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=logsdb
        volumes:
            - /home/cleslley/Documents/logsdb:/data/logsdb
            - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        command: 
            - '--logpath'
            - '/var/log/mongodb/mongod.log'
        ports:
            - 27017:27017

networks: 
    logreader-network:
        driver: bridge
